server:
  port: 8080
  servlet:
    context-path: /vehicle-management

spring:
#  datasource:
#    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:vehicle_management_db}"
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:An@19092003}
#    driver-class-name: org.postgresql.Driver

  datasource:
    url: "jdbc:postgresql://localhost:5432/vehicle_management_db"
    username: postgres
    password: An@19092003
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
