export const apiEndpoints = {
  auth: {
    register: "/public/auth/register",
    resendVerificationEmail: "/public/auth/resend-verification-email",
    forgotPassword: "/public/auth/forgot-password",
  },
  public: {
    pricing: {
      pricePlans: "/public/pricing/price-plans",
      priceRules: "/public/pricing/price-rules",
      ticketTypes: "/public/pricing/ticket-types",
      vehicleTypes: "/public/pricing/vehicle-types",
    },
  },
  dashboard: "/dashboard",
  hardware: {
    devices: "/hardware/devices",
  },
  notifications: {
    activeRoles: "/notifications/active-roles",
    activeBroadcastAnnouncements: "/notifications/broadcast-announcements/active",
    broadcastAnnouncements: "/notifications/broadcast-announcements",
    mine: "/notifications",
    readAll: "/notifications/read-all",
    unreadCount: "/notifications/unread/count",
  },
  parking: {
    gates: "/parking/gates",
    lanes: "/parking/lanes",
    ocrLicensePlate: "/parking/ocr/license-plate",
    parkingLots: "/parking/parking-lots",
    parkingSessions: "/parking/parking-sessions",
    swipes: "/parking/swipes",
    swipeIn: "/parking/swipes/in",
    swipeOut: "/parking/swipes/out",
    zones: "/parking/zones",
  },
  cards: {
    cards: "/access-control/cards",
    lostCards: "/access-control/lost-card-reports",
  },
  accessControl: {
    cards: "/access-control/cards",
    lostCardReports: "/access-control/lost-card-reports",
    subscriptions: "/access-control/subscriptions",
  },
  billing: {
    invoices: "/billing/invoices",
    payments: "/billing/payments",
  },
  catalog: {
    cardTypes: "/catalog/card-types",
    pricePlans: "/catalog/price-plans",
    priceRules: "/catalog/price-rules",
    ticketTypes: "/catalog/ticket-types",
    vehicleTypes: "/catalog/vehicle-types",
    tickets: "/tickets",
    vehicles: "/vehicles",
    visitorParkingFees: "/visitor-parking-fees",
    registrationFees: "/registration-fees",
  },
  customers: {
    customers: "/people/customers",
    customerVehicles: "/people/customer-vehicles",
    histories: "/customer-histories",
  },
  iam: {
    accounts: "/accounts",
    provisionedAccounts: "/iam/accounts/provisioned",
    accountProfile: {
      currentAccess: "/iam/accounts/current-access",
      onboarding: "/iam/accounts/onboarding",
      profile: "/iam/accounts/profile",
      avatar: "/iam/accounts/profile/avatar",
      socialBootstrap: "/iam/accounts/social-bootstrap",
    },
    permissions: "/permissions",
    rolePermissions: (roleId: string) => `/roles/${roleId}/permissions`,
    roles: "/iam/roles",
  },
  people: {
    customerVehicles: "/people/customer-vehicles",
    customers: "/people/customers",
    employees: "/people/employees",
  },
  operations: {
    approveWorkScheduleWeek: "/operations/work-schedules/approve-week",
    customerOnboardingApprovals: "/operations/approval-requests/customer-onboarding",
    internalEmployeeOnboardingApprovals: "/operations/approval-requests/internal-employee-onboarding",
    systemAdminOnboardingApprovals: "/operations/approval-requests/system-admin-onboarding",
    employeeRosterRules: "/operations/employee-roster-rules",
    generateWorkScheduleWeek: "/operations/work-schedules/generate-week",
    shiftAssignments: "/operations/shift-assignments",
    shiftTemplates: "/operations/shift-templates",
    shifts: "/operations/shifts",
    chat: "/operations/chat",
    supportTicketCategories: "/operations/support-ticket-categories",
    supportTickets: "/operations/support-tickets",
  },
} as const;
