export const apiEndpoints = {
  auth: {
    register: "/public/auth/register",
    resendVerificationEmail: "/public/auth/resend-verification-email",
    forgotPassword: "/public/auth/forgot-password",
  },
  public: {
    pricing: {
      pricePlans: "/public/pricing/price-plans",
      priceRules: "/public/pricing/price-rules",
      ticketTypes: "/public/pricing/ticket-types",
      vehicleTypes: "/public/pricing/vehicle-types",
    },
  },
  dashboard: "/dashboard",
  ai: {
    assistantStatus: "/ai/assistant/status",
    assistantMessageStatus: (inputMessageId: string) => `/ai/assistant/messages/${inputMessageId}/status`,
    toolCall: (toolCallId: string) => `/ai/tool-calls/${toolCallId}`,
    messageCitations: (messageId: string) => `/ai/messages/${messageId}/citations`,
    confirmToolCall: (toolCallId: string) => `/ai/tool-calls/${toolCallId}/confirm`,
    denyToolCall: (toolCallId: string) => `/ai/tool-calls/${toolCallId}/deny`,
modelConfigurations: "/ai/models/configurations",
    modelCatalog: "/ai/models/catalog",
    modelCatalogSync: "/ai/models/catalog/sync",
    modelWarnings: "/ai/models/warnings",
    indexVersions: "/ai/index-versions",
    buildIndexVersion: (indexVersionId: string) => `/ai/index-versions/${indexVersionId}/build`,
    activateIndexVersion: (indexVersionId: string) => `/ai/index-versions/${indexVersionId}/activate`,
    rollbackIndexVersion: (indexVersionId: string) => `/ai/index-versions/${indexVersionId}/rollback`,
    knowledgeSources: "/ai/knowledge/sources",
    knowledgeSource: (sourceId: string) => `/ai/knowledge/sources/${sourceId}`,
    deactivateKnowledgeSource: (sourceId: string) => `/ai/knowledge/sources/${sourceId}/deactivate`,
    reactivateKnowledgeSource: (sourceId: string) => `/ai/knowledge/sources/${sourceId}/reactivate`,
    knowledgeSourceDocuments: (sourceId: string) => `/ai/knowledge/sources/${sourceId}/documents`,
    knowledgeDocuments: "/ai/knowledge/documents",
    knowledgeDocument: (documentId: string) => `/ai/knowledge/documents/${documentId}`,
    knowledgeDocumentBlocks: (documentId: string, documentVersion: number) => `/ai/knowledge/documents/${documentId}/blocks?documentVersion=${documentVersion}`,
    knowledgeDocumentChunks: (documentId: string, documentVersion: number) => `/ai/knowledge/documents/${documentId}/chunks?documentVersion=${documentVersion}`,
    uploadKnowledgeDocument: "/ai/knowledge/documents/upload",
    publishKnowledgeDocument: (documentId: string) => `/ai/knowledge/documents/${documentId}/publish`,
    rejectKnowledgeDocument: (documentId: string) => `/ai/knowledge/documents/${documentId}/reject`,
    archiveKnowledgeDocument: (documentId: string) => `/ai/knowledge/documents/${documentId}/archive`,
    reindexKnowledgeDocument: (documentId: string) => `/ai/knowledge/documents/${documentId}/reindex`,
    ingestionJobs: "/ai/knowledge/ingestion-jobs",
    ingestionJob: (jobId: string) => `/ai/knowledge/ingestion-jobs/${jobId}`,
    ingestionJobEvents: (jobId: string) => `/ai/knowledge/ingestion-jobs/${jobId}/events`,
    retryIngestionJob: (jobId: string) => `/ai/knowledge/ingestion-jobs/${jobId}/retry`,
    retrievalTest: "/ai/knowledge/retrieval-tests",
    qualityDashboard: "/ai/knowledge/quality-dashboard",
  },
  hardware: {
    devices: "/hardware/devices",
  },
  notifications: {
    activeRoles: "/notifications/active-roles",
    activeBroadcastAnnouncements: "/notifications/broadcast-announcements/active",
    broadcastAnnouncements: "/notifications/broadcast-announcements",
    mine: "/notifications",
    readAll: "/notifications/read-all",
    unreadCount: "/notifications/unread/count",
  },
  parking: {
    gates: "/parking/gates",
    lanes: "/parking/lanes",
    ocrLicensePlate: "/parking/ocr/license-plate",
    parkingLots: "/parking/parking-lots",
    parkingSessions: "/parking/parking-sessions",
    swipes: "/parking/swipes",
    swipeIn: "/parking/swipes/in",
    swipeOut: "/parking/swipes/out",
    zones: "/parking/zones",
  },
  cards: {
    cards: "/access-control/cards",
    lostCards: "/access-control/lost-card-reports",
  },
  accessControl: {
    cards: "/access-control/cards",
    lostCardReports: "/access-control/lost-card-reports",
    subscriptions: "/access-control/subscriptions",
  },
  billing: {
    invoices: "/billing/invoices",
    payments: "/billing/payments",
  },
  catalog: {
    cardTypes: "/catalog/card-types",
    pricePlans: "/catalog/price-plans",
    priceRules: "/catalog/price-rules",
    vouchers: "/catalog/vouchers",
    customerVoucherBanners: "/catalog/vouchers/promotions",
    ticketTypes: "/catalog/ticket-types",
    vehicleTypes: "/catalog/vehicle-types",
    tickets: "/tickets",
    vehicles: "/vehicles",
    visitorParkingFees: "/visitor-parking-fees",
    registrationFees: "/registration-fees",
  },
  customers: {
    customers: "/people/customers",
    customerVehicles: "/people/customer-vehicles",
    histories: "/customer-histories",
  },
  iam: {
    accounts: "/accounts",
    partnerRegistrations: "/iam/partner-registrations",
    provisionedAccounts: "/iam/accounts/provisioned",
    accountProfile: {
      currentAccess: "/iam/accounts/current-access",
      onboarding: "/iam/accounts/onboarding",
      profile: "/iam/accounts/profile",
      avatar: "/iam/accounts/profile/avatar",
      socialBootstrap: "/iam/accounts/social-bootstrap",
    },
    permissions: "/permissions",
    rolePermissions: (roleId: string) => `/roles/${roleId}/permissions`,
    roles: "/iam/roles",
  },
  people: {
    customerVehicles: "/people/customer-vehicles",
    customers: "/people/customers",
    employees: "/people/employees",
  },
  operations: {
    approveWorkScheduleWeek: "/operations/work-schedules/approve-week",
    customerOnboardingApprovals: "/operations/approval-requests/customer-onboarding",
    internalEmployeeOnboardingApprovals: "/operations/approval-requests/internal-employee-onboarding",
    onboardingApprovalSummary: "/operations/approval-requests/onboarding-summary",
    systemAdminOnboardingApprovals: "/operations/approval-requests/system-admin-onboarding",
    employeeRosterRules: "/operations/employee-roster-rules",
    generateWorkScheduleWeek: "/operations/work-schedules/generate-week",
    shiftAssignments: "/operations/shift-assignments",
    shiftTemplates: "/operations/shift-templates",
    shifts: "/operations/shifts",
    chat: "/operations/chat",
    supportTicketCategories: "/operations/support-ticket-categories",
    supportTickets: "/operations/support-tickets",
    supportAssistantConversation: "/operations/support-tickets/assistant-conversation",
    supportTicketCustomerConversation: (ticketId: string) => `/operations/support-tickets/${ticketId}/customer-conversation`,
    supportTicketEscalations: "/operations/support-ticket-escalations",
    supportTicketEscalationForTicket: (ticketId: string) => `/operations/support-tickets/${ticketId}/escalations`,
    supportTicketsFromConversation: (conversationId: string) => `/operations/support-tickets/from-conversations/${conversationId}`,
  },
} as const;
